1# Financial assumptions

**Lesson:** Assumptions, Seasonality and Variance  
_Financial Forecasting in Python_

📄 Notes: [01 - Financial assumptions](docs/01%20-%20Financial%20assumptions.md)

## Overview

Set the growth and cost assumptions that drive a financial forecast.

## Learning objectives

- Explain the role of assumptions as the drivers behind every financial forecast.
- Apply a growth-rate assumption to project a figure forward over multiple periods.
- Link assumptions together (e.g. a cost ratio on top of a sales forecast) to project dependent line items.

## Setup

In [15]:
import sys; sys.path.insert(0, '../../src')

# import numpy as np
# import pandas as pd
# import matplotlib.pyplot as plt

from ffp import sample_prices, error_report  # shared helpers

## Walkthrough

In [16]:
# A forecast starts from a base figure and applies an assumption to it.
# Here: last year's sales grown by an assumed annual growth rate.
base_sales = 5000
growth = 0.05  # assume 5% annual growth

next_year = base_sales * (1 + growth)
print("Base sales:        {}".format(base_sales))
print("Assumed growth:    {:.0%}".format(growth))
print("Next year forecast: {:.2f}".format(next_year))

Base sales:        5000
Assumed growth:    5%
Next year forecast: 5250.00


**Exercise 1 - Applying a growth assumption**

Every forecast rests on assumptions. The simplest is a growth rate: the percentage by which a figure is expected to change each period.

A company closed the year with **5,000** in sales and expects sales to grow by **5%** each year. Project the sales figure forward for the **next 3 years**, rounding each year to 2 decimal places, and collect the results in a list called `forecast`.

Remember that applying growth means multiplying by `(1 + growth)` once per period.

In [17]:
# Starting sales and the annual growth assumption
sales = 5000
growth = 0.05  # 5% per year

# Project sales forward for the next 3 years
forecast = []
for year in range(1, 4):
    sales = sales * (1 + growth)
    forecast.append(round(sales, 2))

# Print the result
print("Projected sales for the next 3 years: {}".format(forecast))

Projected sales for the next 3 years: [5250.0, 5512.5, 5788.12]


**Exercise 2 - Growth as a formula**

Looping works, but when the growth rate is constant you can jump straight to any future period with the compound-growth formula:

`future_value = base * (1 + growth) ** periods`

Using the same base sales of **5,000** and **5%** annual growth, calculate the sales figure **3 years** out in a single expression and confirm it matches the last value from Exercise 1.

In [18]:
# Base sales, growth assumption, and number of years to project
base_sales = 5000
growth = 0.05
years = 3

# Future value of sales after `years` of compounding growth
future_sales = base_sales * (1 + growth) ** years

print("Sales after {} years: {:.2f}".format(years, future_sales))

Sales after 3 years: 5788.13


**Exercise 3 - Linking assumptions together**

Assumptions rarely stand alone: one line item often drives another. A common example is **cost of goods sold (COGS)** expressed as a percentage of sales — so once sales are forecast, COGS follows automatically.

Take the sales forecast from Exercise 1 (`[5250.0, 5512.5, 5788.12]`) and an assumption that **COGS is 60% of sales**. For each year, print the sales, the resulting COGS, and the **gross profit** (sales − COGS).

In [19]:
# Sales forecast from Exercise 1 and a cost assumption
sales_forecast = [5250.0, 5512.5, 5788.12]
cogs_pct = 0.60  # assume COGS is 60% of sales

# Forecast COGS and gross profit for each year
for i, sales in enumerate(sales_forecast, start=1):
    cogs = sales * cogs_pct
    gross_profit = sales - cogs
    print("Year {}: sales={:.2f}, COGS={:.2f}, gross profit={:.2f}".format(
        i, sales, cogs, gross_profit))

Year 1: sales=5250.00, COGS=3150.00, gross profit=2100.00
Year 2: sales=5512.50, COGS=3307.50, gross profit=2205.00
Year 3: sales=5788.12, COGS=3472.87, gross profit=2315.25


**Exercise 4 - Weighted probability**

Txs Tools, a company selling hardware tools, is looking to expand out of their home market A into Market B. They have done some market research, and have received the following numeric probabilities:

| Sales Level (USD) | Probability (%) |
|-------------------|-----------------|
| 0                 | 5               |
| 200               | 10              |
| 300               | 40              |
| 500               | 20              |
| 800               | 25              |

Txs Tools will only be motivated to expand if they can have reasonable assurance that they will achieve sales of 400 or more. To manage the different forecast sales probabilities, Txs Tools have asked you to calculate the weighted probability.

In [20]:
# Create the combined list for sales and probability
sales_probability = ['0|0.05', '200|0.1', '300|0.4', '500|0.2', '800|0.25']
weighted_probability = 0

# Create a for loop to calculate the weighted probability
for pair in sales_probability:
    parts = pair.split('|')
    weighted_probability += int(parts[0]) * float(parts[1])

# Print the weighted probability result
print("The weighted probability is {}.".format(weighted_probability))

The weighted probability is 440.0.


**Exercise 5 - Market Sentiment**

Txs Tools has forecast sales of 500 in January, with an expected increase of 5% per month for the rest of the quarter.

However, this is dependent on the market sentiment. Based on historical trends, the following information has been provided:

- If the market sentiment drops below 0.6 then the sales will only be realized at an increase of 2% per month.
- If market sentiment increases above 0.8. then sales are expected to increase by 7%.

In [21]:
# Create the computevariance function
def computevariance(amount, sentiment):
 if (sentiment < 0.6):
  res = amount + (amount * 0.02)
 elif (sentiment > 0.8):
  res = amount + (amount * 0.07)
 else:
  res = amount + (amount * 0.05)
 return res

# Compute the variance for jan, feb and mar
jan = computevariance(500, 0.5)
feb = computevariance(500, 0.65)
mar = computevariance(500, 0.85)

print("The forecast sales considering variance due to market sentiment is {} for Jan, {} for Feb, and {} for Mar.".format(jan, feb, mar))

The forecast sales considering variance due to market sentiment is 510.0 for Jan, 525.0 for Feb, and 535.0 for Mar.


**Exercise 6 - Dependecies and Sensitivities in Financial Forecasting**


6.1 - Explaining forecasting dependencies and sensitivities
Unlike assumptions, which are set variables that drive best guess estimates, dependencies and sensitivities are interlinked variables, where change in one variable impacts another, to a greater or lesser degree.

6.2 - Working with dependencies and sensitivities in Python
In Python, we can use the following structure for our code. Basically, we can create an if statement that can be used to calculate the result depending on if the conditions are met. Look at this example. During the month of December, we expect to have rush orders for the holidays, pushing up delivery costs by 10%. Assume the variables have been defined, then the code would look as follows:


In [22]:
# Assume the base delivery cost and current month have been defined
delivery_cost = 1000
month = 'December'

# December rush orders push delivery costs up by 10%
if month == 'December':
    delivery_cost = delivery_cost + (delivery_cost * 0.10)

print("The delivery cost for {} is {:.2f} USD.".format(month, delivery_cost))

The delivery cost for December is 1100.00 USD.


**Exercise 6.3 Assigning dependencies for sales and COGS**

Txs Tools have built a monthly forecast for their gross profit. This will rely on dependencies for Sales and COGS.

Set the dependencies for sales and cogs based on the information below:

- Sales dependency sales_dep: The sale price is the net price after 1 USD commission. Commissions paid increase from 1 USD per unit to 2 USD per unit for every unit above 350 units sold.
- Cost dependency cost_dep: When sales per unit increase above 500 units, an additional production line needs to be used, causing an increase in the cost per unit above 500 of 2 USD per unit.

The baseline sale price per unit (base_sales_price) is 15 USD and the baseline cost per unit (base_cost_price) is 7 USD.



In [23]:
# Baseline prices and the forecast unit sales for this scenario
base_sales_price = 15
base_cost_price = 7
sales = 700  # forecast units sold

# Set the Sales Dependency
if sales >= 350:
    sales_dep = (350 * base_sales_price) + ((sales - 350) * (base_sales_price - 1))
else:
    sales_dep = sales * base_sales_price

# Print the results
print("The sales dependency is {} USD.".format(sales_dep))

# Set the Cost Dependency
if sales >= 500:
    cost_dep = (500 * base_cost_price) + ((sales - 500) * (base_cost_price + 2))
else:
    cost_dep = sales * base_cost_price

# Print the results
print("The cost dependency is {} USD.".format(cost_dep))

The sales dependency is 10150 USD.
The cost dependency is 5300 USD.


**Exercise 6.4 Building a sensitivity analysis for gross profit**

Txs Tools is now ready to use these dependencies in the gross profit forecast.

The following forecast unit sales have been provided:

Jul = 700 Aug = 350 Sep = 650

The dependencies for sales and cogs are based on the following:

Sales dependency sales_dep: The sale price is the net price after 1 USD commission. Commissions paid increase from 1 USD per unit to 2 USD per unit for every unit above 350 units sold.
Cost dependency cost_dep: When sales per unit increase above 500 units, an additional production line needs to be used, causing an increase in the cost per unit above 500 of 2 USD per unit.
The basic cost price base_cost_price = 7 and basic sales price base_sales_price = 15 has already been set.

In [24]:
# Baseline prices (already set in the earlier exercise, repeated here so this cell stands alone)
base_sales_price = 15
base_cost_price = 7

# Create the sales_usd list
sales_usd = [700, 350, 650]

# Create the if statement to calculate the forecast_gross_profit
for sales in sales_usd:
    if sales > 350:
        sales_dep = (350 * base_sales_price) + ((sales - 350) * (base_sales_price - 1))
    else:
        sales_dep = sales * base_sales_price
    if sales > 500:
        cost_dep = (500 * base_cost_price) + ((sales - 500) * (base_cost_price + 2))
    else:
        cost_dep = sales * base_cost_price
    forecast_gross_profit = sales_dep - cost_dep

    # Print the result
    print("The gross profit forecast for a sale unit value of {} is {} USD.".format(sales, forecast_gross_profit))

The gross profit forecast for a sale unit value of 700 is 4850 USD.
The gross profit forecast for a sale unit value of 350 is 2800 USD.
The gross profit forecast for a sale unit value of 650 is 4600 USD.


**Exercise 6.5 - Assigning dependencies for expenses**

Txs Tools wants to assign a dependency for its operating expenses, particularly admin salaries.

The conditions are as follows:

Admin expenses increase in July and August (Jul and Aug) as temporary workers need to be hired to cover the summer holiday.
The increase is based on the number of employees taking holidays during that time. For the current year, the value for August is emp_leave = 6 (6 employees expected to take leave).
The cost is 80 USD per temp employee hired.


In [25]:
emp_leave = 6
# Set the admin dependency
if emp_leave > 0:
    admin_dep = emp_leave * 80

# Print the results
print("The admin dependency for August is {} USD.".format(admin_dep))

The admin dependency for August is 480 USD.


**Exercise 7 - Build a sensitivity analysis for the net profit**

Txs Tools has provided the following forecast admin cost in USD based on full-time employees:

Jul = 1500 Aug = 1500 Sep = 1500

Build the forecast net profit forecast_net_profit when emp_leave = [6, 6, 0] and the cost per temp employee is 80 USD.

In addition to emp_leave and admin_usd, forecast gross profit has already been provided for you as forecast_gross_profit.



In [26]:
admin_usd = [1500, 1500, 1500]
emp_leave = [6, 6, 0]
forecast_gross_profit = [4850, 2800, 4600]
forecast_net_profit = []
index = 0

for admin in admin_usd:
    temp = emp_leave[index]
    if temp > 0:
        admin_dep = temp * 80 + admin
    else:
        admin_dep = admin
    forecast_net_profit.append(forecast_gross_profit[index] - admin_dep)
    index += 1

print("The forecast net profit is: {}".format(forecast_net_profit))

The forecast net profit is: [2870, 820, 3100]


## Summary

Recap the key points in the notes: [01 - Financial assumptions](docs/01%20-%20Financial%20assumptions.md)

Next up: [02 - Variance](02-variance.ipynb), where we measure how far actual results diverge from these forecasts.